// In a real app, this would be fetched from the backend or a file.
// Embedding here for the standalone MVP requirements.

export const MASTER_DATA_JSONL = `
{"input": "Provide the master data details for unit 4BHK-C8-SF (flat C8-SF).", "output": "Unit_ID: 4BHK-C8-SF\\nFlat no: C8\\nFloor: SF\\nClient Name: S.Jora Singh and S. Bahadur Singh\\nMeter No.: 21129958\\nFixed Charge: ₹1890\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729933.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 4BHK-C8-FF (flat C8-FF).", "output": "Unit_ID: 4BHK-C8-FF\\nFlat no: C8\\nFloor: FF\\nClient Name: Jaswant  singh randhawa\\nMeter No.: 21129916\\nFixed Charge: ₹1890\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729933.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 4BHK-C8-GF (flat C8-GF).", "output": "Unit_ID: 4BHK-C8-GF\\nFlat no: C8\\nFloor: GF\\nClient Name: S.Jora Singh and S. Bahadur Singh\\nMeter No.: 24114213\\nFixed Charge: ₹1890\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729933.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 4BHK-C9-SF (flat C9-SF).", "output": "Unit_ID: 4BHK-C9-SF\\nFlat no: C9\\nFloor: SF\\nClient Name: RAJBIR KAUR W/o Sukhinder Singh\\nMeter No.: 528011\\nFixed Charge: ₹1890\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729933.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 4BHK-C9-FF (flat C9-FF).", "output": "Unit_ID: 4BHK-C9-FF\\nFlat no: C9\\nFloor: FF\\nClient Name: JARNAIL SINGH POWAR\\nMeter No.: 22102869\\nFixed Charge: ₹1890\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729933.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 4BHK-C9-GF (flat C9-GF).", "output": "Unit_ID: 4BHK-C9-GF\\nFlat no: C9\\nFloor: GF\\nClient Name: JASPAL SOHI\\nMeter No.: 528007\\nFixed Charge: ₹1890\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729933.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 4BHK-C16-SF (flat C16-SF).", "output": "Unit_ID: 4BHK-C16-SF\\nFlat no: C16\\nFloor: SF\\nClient Name: balbir kaur jabble\\nMeter No.: 528010\\nFixed Charge: ₹1890\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729933.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 4BHK-C16-FF (flat C16-FF).", "output": "Unit_ID: 4BHK-C16-FF\\nFlat no: C16\\nFloor: FF\\nClient Name: Dr. Sant Singh Dhillon\\nMeter No.: 24114215\\nFixed Charge: ₹1890\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729933.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 4BHK-C16-GF (flat C16-GF).", "output": "Unit_ID: 4BHK-C16-GF\\nFlat no: C16\\nFloor: GF\\nClient Name: Mrs. Neena Sood and Sudesh Sood\\nMeter No.: 528004\\nFixed Charge: ₹1890\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729933.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 4BHK-C17-SF (flat C17-SF).", "output": "Unit_ID: 4BHK-C17-SF\\nFlat no: C17\\nFloor: SF\\nClient Name: Mr. Rajan Kumar s/o Ram Parshad Sharma\\nMeter No.: 528014\\nFixed Charge: ₹1890\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729933.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 4BHK-C17-FF (flat C17-FF).", "output": "Unit_ID: 4BHK-C17-FF\\nFlat no: C17\\nFloor: FF\\nClient Name: Unique Contructions\\nMeter No.: 22102921\\nFixed Charge: ₹1890\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729933.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 4BHK-C17-GF (flat C17-GF).", "output": "Unit_ID: 4BHK-C17-GF\\nFlat no: C17\\nFloor: GF\\nClient Name: GIRDHARI LAL CHOPRA\\nMeter No.: 21082127\\nFixed Charge: ₹1890\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729933.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 4BHK-C10-SF (flat C10-SF).", "output": "Unit_ID: 4BHK-C10-SF\\nFlat no: C10\\nFloor: SF\\nClient Name: Balbir Singh\\nMeter No.: 20054610\\nFixed Charge: ₹1890\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729933.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 4BHK-C10-FF (flat C10-FF).", "output": "Unit_ID: 4BHK-C10-FF\\nFlat no: C10\\nFloor: FF\\nClient Name: Daljit Kaur\\nMeter No.: 20054604\\nFixed Charge: ₹1890\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729933.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 4BHK-C10-GF (flat C10-GF).", "output": "Unit_ID: 4BHK-C10-GF\\nFlat no: C10\\nFloor: GF\\nClient Name: Regent Land Holdings Pvt Ltd\\nMeter No.: 20054606\\nFixed Charge: ₹1890\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729933.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 4BHK-C11-SF (flat C11-SF).", "output": "Unit_ID: 4BHK-C11-SF\\nFlat no: C11\\nFloor: SF\\nClient Name: Kanwar Shekhar C Sharma\\nMeter No.: 20054956\\nFixed Charge: ₹1890\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729933.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 4BHK-C11-FF (flat C11-FF).", "output": "Unit_ID: 4BHK-C11-FF\\nFlat no: C11\\nFloor: FF\\nClient Name: Baljit Sharma\\nMeter No.: 20054955\\nFixed Charge: ₹1890\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729933.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 4BHK-C11-GF (flat C11-GF).", "output": "Unit_ID: 4BHK-C11-GF\\nFlat no: C11\\nFloor: GF\\nClient Name: RACHNA JAIN\\nMeter No.: 20054606\\nFixed Charge: ₹1890\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729933.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 4BHK-C14-SF (flat C14-SF).", "output": "Unit_ID: 4BHK-C14-SF\\nFlat no: C14\\nFloor: SF\\nClient Name: Regent Land Holdings Pvt Ltd\\nMeter No.: 21082169\\nFixed Charge: ₹1890\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729933.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 4BHK-C14-FF (flat C14-FF).", "output": "Unit_ID: 4BHK-C14-FF\\nFlat no: C14\\nFloor: FF\\nClient Name: POOJA TRIKHA AND ASHIMA TRIKHA\\nMeter No.: 21082169\\nFixed Charge: ₹1890\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729933.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 4BHK-C14-GF (flat C14-GF).", "output": "Unit_ID: 4BHK-C14-GF\\nFlat no: C14\\nFloor: GF\\nClient Name: BALBIR RAI TAHEEM\\nMeter No.: 21082171\\nFixed Charge: ₹1890\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729933.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 4BHK-C15-SF (flat C15-SF).", "output": "Unit_ID: 4BHK-C15-SF\\nFlat no: C15\\nFloor: SF\\nClient Name: Regent Land Holdings Pvt Ltd\\nMeter No.: 21082173\\nFixed Charge: ₹1890\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729933.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 4BHK-C15-FF (flat C15-FF).", "output": "Unit_ID: 4BHK-C15-FF\\nFlat no: C15\\nFloor: FF\\nClient Name: Harjinder Singh\\nMeter No.: 21082173\\nFixed Charge: ₹1890\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729933.0\\nPhone Number: 918288860588.0\\nEmail: prabnoor.shah@gmail.com"}
{"input": "Provide the master data details for unit 4BHK-C15-GF (flat C15-GF).", "output": "Unit_ID: 4BHK-C15-GF\\nFlat no: C15\\nFloor: GF\\nClient Name: Sumit Wadhera\\nMeter No.: 21082175\\nFixed Charge: ₹1890\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729933.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 5BHK-B5-SF (flat B5-SF).", "output": "Unit_ID: 5BHK-B5-SF\\nFlat no: B5\\nFloor: SF\\nClient Name: Satinder Kaur\\nMeter No.: 19152137\\nFixed Charge: ₹2311\\nRate Per Unit: ₹12\\nWater Motor Meter No: 87923504.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 5BHK-B5-FF (flat B5-FF).", "output": "Unit_ID: 5BHK-B5-FF\\nFlat no: B5\\nFloor: FF\\nClient Name: Komal Bhandari\\nMeter No.: 19152141\\nFixed Charge: ₹2311\\nRate Per Unit: ₹12\\nWater Motor Meter No: 87923504.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 5BHK-B5-GF (flat B5-GF).", "output": "Unit_ID: 5BHK-B5-GF\\nFlat no: B5\\nFloor: GF\\nClient Name: Deepak Kapila\\nMeter No.: 19152166\\nFixed Charge: ₹2311\\nRate Per Unit: ₹12\\nWater Motor Meter No: 87923504.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 5BHK-B6-SF (flat B6-SF).", "output": "Unit_ID: 5BHK-B6-SF\\nFlat no: B6\\nFloor: SF\\nClient Name: Satinder Bassi\\nMeter No.: 19152196\\nFixed Charge: ₹2311\\nRate Per Unit: ₹12\\nWater Motor Meter No: 87923504.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 5BHK-B6-FF (flat B6-FF).", "output": "Unit_ID: 5BHK-B6-FF\\nFlat no: B6\\nFloor: FF\\nClient Name: Barinder Singh Bhullar\\nMeter No.: 19152193\\nFixed Charge: ₹2311\\nRate Per Unit: ₹12\\nWater Motor Meter No: 87923504.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 5BHK-B6-GF (flat B6-GF).", "output": "Unit_ID: 5BHK-B6-GF\\nFlat no: B6\\nFloor: GF\\nClient Name: Nitin Tuteja\\nMeter No.: 19152194\\nFixed Charge: ₹2311\\nRate Per Unit: ₹12\\nWater Motor Meter No: 87923504.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 5BHK-B17-SF (flat B17-SF).", "output": "Unit_ID: 5BHK-B17-SF\\nFlat no: B17\\nFloor: SF\\nClient Name: Romy Gupta\\nMeter No.: 19152158\\nFixed Charge: ₹2311\\nRate Per Unit: ₹12\\nWater Motor Meter No: 87923504.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 5BHK-B17-FF (flat B17-FF).", "output": "Unit_ID: 5BHK-B17-FF\\nFlat no: B17\\nFloor: FF\\nClient Name: Kulwant Rai\\nMeter No.: 19152159\\nFixed Charge: ₹2311\\nRate Per Unit: ₹12\\nWater Motor Meter No: 87923504.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 5BHK-B17-GF (flat B17-GF).", "output": "Unit_ID: 5BHK-B17-GF\\nFlat no: B17\\nFloor: GF\\nClient Name: Manjit Kaur\\nMeter No.: 19152160\\nFixed Charge: ₹2311\\nRate Per Unit: ₹12\\nWater Motor Meter No: 87923504.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 5BHK-B18-SF (flat B18-SF).", "output": "Unit_ID: 5BHK-B18-SF\\nFlat no: B18\\nFloor: SF\\nClient Name: Birbal Sharma, Amritpal Singh\\nMeter No.: 19152171\\nFixed Charge: ₹2311\\nRate Per Unit: ₹12\\nWater Motor Meter No: 87923504.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 5BHK-B18-FF (flat B18-FF).", "output": "Unit_ID: 5BHK-B18-FF\\nFlat no: B18\\nFloor: FF\\nClient Name: Vandana Aggarwal\\nMeter No.: 19152195\\nFixed Charge: ₹2311\\nRate Per Unit: ₹12\\nWater Motor Meter No: 87923504.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 5BHK-B18-GF (flat B18-GF).", "output": "Unit_ID: 5BHK-B18-GF\\nFlat no: B18\\nFloor: GF\\nClient Name: Indu Aggarwal\\nMeter No.: 19152157\\nFixed Charge: ₹2311\\nRate Per Unit: ₹12\\nWater Motor Meter No: 87923504.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-D1-SF (flat D1-SF).", "output": "Unit_ID: 2BHK-D1-SF\\nFlat no: D1\\nFloor: SF\\nClient Name: Regent Land Holdings Pvt Ltd\\nMeter No.: 19152022\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 90199696.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-D1-FF (flat D1-FF).", "output": "Unit_ID: 2BHK-D1-FF\\nFlat no: D1\\nFloor: FF\\nClient Name: Prem Rana\\nMeter No.: 19152221\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 90199696.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-D1-GF (flat D1-GF).", "output": "Unit_ID: 2BHK-D1-GF\\nFlat no: D1\\nFloor: GF\\nClient Name: Vinod Khosla\\nMeter No.: 22102860\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 90199696.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-D2-SF (flat D2-SF).", "output": "Unit_ID: 2BHK-D2-SF\\nFlat no: D2\\nFloor: SF\\nClient Name: Rajesh Sabharwal\\nMeter No.: 19151950\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 90199696.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-D2-FF (flat D2-FF).", "output": "Unit_ID: 2BHK-D2-FF\\nFlat no: D2\\nFloor: FF\\nClient Name: Mohammad Qaqoo\\nMeter No.: 21082126\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 90199696.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-D2-GF (flat D2-GF).", "output": "Unit_ID: 2BHK-D2-GF\\nFlat no: D2\\nFloor: GF\\nClient Name: Regent Land Holdings Pvt Ltd\\nMeter No.: 19151950\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 90199696.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-D3-SF (flat D3-SF).", "output": "Unit_ID: 2BHK-D3-SF\\nFlat no: D3\\nFloor: SF\\nClient Name: Regent Land Holdings Pvt Ltd\\nMeter No.: 19152248\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 90199696.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-D3-FF (flat D3-FF).", "output": "Unit_ID: 2BHK-D3-FF\\nFlat no: D3\\nFloor: FF\\nClient Name: Dr. Prem Rana\\nMeter No.: 19152248\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 90199696.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-D3-GF (flat D3-GF).", "output": "Unit_ID: 2BHK-D3-GF\\nFlat no: D3\\nFloor: GF\\nClient Name: Iqbal Singh\\nMeter No.: 19152248\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 90199696.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-D4-SF (flat D4-SF).", "output": "Unit_ID: 2BHK-D4-SF\\nFlat no: D4\\nFloor: SF\\nClient Name: Regent Land Holdings Pvt Ltd\\nMeter No.: 19152170\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 90199696.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-D4-FF (flat D4-FF).", "output": "Unit_ID: 2BHK-D4-FF\\nFlat no: D4\\nFloor: FF\\nClient Name: Aarti Garg\\nMeter No.: 19152170\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 90199696.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-D4-GF (flat D4-GF).", "output": "Unit_ID: 2BHK-D4-GF\\nFlat no: D4\\nFloor: GF\\nClient Name: Rashma Oberoi\\nMeter No.: 19152170\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 90199696.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-D6-SF (flat D6-SF).", "output": "Unit_ID: 2BHK-D6-SF\\nFlat no: D6\\nFloor: SF\\nClient Name: Manju Mahajan\\nMeter No.: 22102735\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 19152168.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-D6-FF (flat D6-FF).", "output": "Unit_ID: 2BHK-D6-FF\\nFlat no: D6\\nFloor: FF\\nClient Name: Kuldeep Singh\\nMeter No.: 22102733\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 19152168.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-D6-GF (flat D6-GF).", "output": "Unit_ID: 2BHK-D6-GF\\nFlat no: D6\\nFloor: GF\\nClient Name: Santosh Gambhir\\nMeter No.: 19152140\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 19152168.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-D7-SF (flat D7-SF).", "output": "Unit_ID: 2BHK-D7-SF\\nFlat no: D7\\nFloor: SF\\nClient Name: Gursharan Singh\\nMeter No.: 19152192\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 19152168.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-D7-FF (flat D7-FF).", "output": "Unit_ID: 2BHK-D7-FF\\nFlat no: D7\\nFloor: FF\\nClient Name: Rashma Oberoi\\nMeter No.: 22102732\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 19152168.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-D7-GF (flat D7-GF).", "output": "Unit_ID: 2BHK-D7-GF\\nFlat no: D7\\nFloor: GF\\nClient Name: Navdeep Kaur\\nMeter No.: 19152138\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 19152168.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-D8-SF (flat D8-SF).", "output": "Unit_ID: 2BHK-D8-SF\\nFlat no: D8\\nFloor: SF\\nClient Name: Anshu Gupta\\nMeter No.: 19152165\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 19152168.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-D8-FF (flat D8-FF).", "output": "Unit_ID: 2BHK-D8-FF\\nFlat no: D8\\nFloor: FF\\nClient Name: Ashok Kumar Mehra\\nMeter No.: 19152165\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 19152168.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-D8-GF (flat D8-GF).", "output": "Unit_ID: 2BHK-D8-GF\\nFlat no: D8\\nFloor: GF\\nClient Name: Dr. Navpreet Singh\\nMeter No.: 19152165\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 19152168.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-D9-SF (flat D9-SF).", "output": "Unit_ID: 2BHK-D9-SF\\nFlat no: D9\\nFloor: SF\\nClient Name: Jupinder Sandhu\\nMeter No.: 19152143\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 19152168.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-D9-FF (flat D9-FF).", "output": "Unit_ID: 2BHK-D9-FF\\nFlat no: D9\\nFloor: FF\\nClient Name: Rajbir Singh\\nMeter No.: 19152139\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 19152168.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-D9-GF (flat D9-GF).", "output": "Unit_ID: 2BHK-D9-GF\\nFlat no: D9\\nFloor: GF\\nClient Name: Surinder Kaur Ranger\\nMeter No.: 19152167\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 19152168.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-D10-SF (flat D10-SF).", "output": "Unit_ID: 2BHK-D10-SF\\nFlat no: D10\\nFloor: SF\\nClient Name: Anju Mahajan\\nMeter No.: 19152144\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 19152168.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-D10-FF (flat D10-FF).", "output": "Unit_ID: 2BHK-D10-FF\\nFlat no: D10\\nFloor: FF\\nClient Name: Lakhwinder Singh\\nMeter No.: 19152144\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 19152168.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-D10-GF (flat D10-GF).", "output": "Unit_ID: 2BHK-D10-GF\\nFlat no: D10\\nFloor: GF\\nClient Name: Robin Singal\\nMeter No.: 19152144\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 19152168.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-D11-SF (flat D11-SF).", "output": "Unit_ID: 2BHK-D11-SF\\nFlat no: D11\\nFloor: SF\\nClient Name: Aarti singh\\nMeter No.: 19152142\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 19152168.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-D11-FF (flat D11-FF).", "output": "Unit_ID: 2BHK-D11-FF\\nFlat no: D11\\nFloor: FF\\nClient Name: Inderpal Ahullwalia \\nMeter No.: 22102730\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 19152168.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-D11-GF (flat D11-GF).", "output": "Unit_ID: 2BHK-D11-GF\\nFlat no: D11\\nFloor: GF\\nClient Name: Amritbeer Kaur,Harkrishan Singh\\nMeter No.: 22102734\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 19152168.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F2-SF (flat F2-SF).", "output": "Unit_ID: 2BHK-F2-SF\\nFlat no: F2\\nFloor: SF\\nClient Name: Manjit Kaur Gill\\nMeter No.: 20054611\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729926.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F2-FF (flat F2-FF).", "output": "Unit_ID: 2BHK-F2-FF\\nFlat no: F2\\nFloor: FF\\nClient Name: NISHAN SINGH\\nMeter No.: 20054607\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729926.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F2-GF (flat F2-GF).", "output": "Unit_ID: 2BHK-F2-GF\\nFlat no: F2\\nFloor: GF\\nClient Name: MANMOHAN SINGH\\nMeter No.: 20054603\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729926.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F3-SF (flat F3-SF).", "output": "Unit_ID: 2BHK-F3-SF\\nFlat no: F3\\nFloor: SF\\nClient Name: Ms. Madhu Bala and VINOD KUMAR\\nMeter No.: 19152177\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729926.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F3-FF (flat F3-FF).", "output": "Unit_ID: 2BHK-F3-FF\\nFlat no: F3\\nFloor: FF\\nClient Name: Ranjit kalsi\\nMeter No.: 19152177\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729926.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F3-GF (flat F3-GF).", "output": "Unit_ID: 2BHK-F3-GF\\nFlat no: F3\\nFloor: GF\\nClient Name: Sehdev Singh\\nMeter No.: 19152177\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729926.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F4-SF (flat F4-SF).", "output": "Unit_ID: 2BHK-F4-SF\\nFlat no: F4\\nFloor: SF\\nClient Name: Mr. Varun Vasudeva s/o Rajan Vasudev and Mrs. Sonia Vasudeva w/o Mr. Varun Vasudeva\\nMeter No.: 19152229\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729926.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F4-FF (flat F4-FF).", "output": "Unit_ID: 2BHK-F4-FF\\nFlat no: F4\\nFloor: FF\\nClient Name: Ravinder Singh\\nMeter No.: 19152229\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729926.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F4-GF (flat F4-GF).", "output": "Unit_ID: 2BHK-F4-GF\\nFlat no: F4\\nFloor: GF\\nClient Name: Ashok Oberoi\\nMeter No.: 19152229\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729926.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F5-SF (flat F5-SF).", "output": "Unit_ID: 2BHK-F5-SF\\nFlat no: F5\\nFloor: SF\\nClient Name: Regent Land Holdings Pvt Ltd\\nMeter No.: 19151878\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729926.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F5-FF (flat F5-FF).", "output": "Unit_ID: 2BHK-F5-FF\\nFlat no: F5\\nFloor: FF\\nClient Name: S. Gurpreet Singh s/o Amrik Singh\\nMeter No.: 19151878\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729926.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F5-GF (flat F5-GF).", "output": "Unit_ID: 2BHK-F5-GF\\nFlat no: F5\\nFloor: GF\\nClient Name: Regent Land Holdings Pvt Ltd\\nMeter No.: 19151878\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729926.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F6-SF (flat F6-SF).", "output": "Unit_ID: 2BHK-F6-SF\\nFlat no: F6\\nFloor: SF\\nClient Name: SUNIL PAWA, PARDEEP SINGH & SAROJ KUMARI\\nMeter No.: 19152155\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729926.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F6-FF (flat F6-FF).", "output": "Unit_ID: 2BHK-F6-FF\\nFlat no: F6\\nFloor: FF\\nClient Name: Regent Land Holdings Pvt Ltd\\nMeter No.: 19152155\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729926.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F6-GF (flat F6-GF).", "output": "Unit_ID: 2BHK-F6-GF\\nFlat no: F6\\nFloor: GF\\nClient Name: Regent Land Holdings Pvt Ltd\\nMeter No.: 19152155\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729926.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F7-SF (flat F7-SF).", "output": "Unit_ID: 2BHK-F7-SF\\nFlat no: F7\\nFloor: SF\\nClient Name: Sh. Sanjay Bhardwaj AND Sh. Vikas Bhardwaj s/o Sh. R. C. Bhardawaj\\nMeter No.: 20054602\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 97701102.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F7-FF (flat F7-FF).", "output": "Unit_ID: 2BHK-F7-FF\\nFlat no: F7\\nFloor: FF\\nClient Name: Menu sehgal\\nMeter No.: 19152232\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 97701102.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F7-GF (flat F7-GF).", "output": "Unit_ID: 2BHK-F7-GF\\nFlat no: F7\\nFloor: GF\\nClient Name: Regent Land Holdings Pvt Ltd\\nMeter No.: 20054605\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 97701102.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F8-SF (flat F8-SF).", "output": "Unit_ID: 2BHK-F8-SF\\nFlat no: F8\\nFloor: SF\\nClient Name: AMANJOT & ANUPREET KAUR\\nMeter No.: 24197359\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 97701102.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F8-FF (flat F8-FF).", "output": "Unit_ID: 2BHK-F8-FF\\nFlat no: F8\\nFloor: FF\\nClient Name: Mr. Manbir Kaur w/o S. Amarpal Singh\\nMeter No.: 24195893\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 97701102.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F8-GF (flat F8-GF).", "output": "Unit_ID: 2BHK-F8-GF\\nFlat no: F8\\nFloor: GF\\nClient Name: Ruchi ad Ruhi\\nMeter No.: 20054609\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 97701102.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F9-SF (flat F9-SF).", "output": "Unit_ID: 2BHK-F9-SF\\nFlat no: F9\\nFloor: SF\\nClient Name: Rashma Oberai\\nMeter No.: 22102737\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 97701102.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F9-FF (flat F9-FF).", "output": "Unit_ID: 2BHK-F9-FF\\nFlat no: F9\\nFloor: FF\\nClient Name: Rajwant Singh s/o Chanan Singh \\nMeter No.: 22102738\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 97701102.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F9-GF (flat F9-GF).", "output": "Unit_ID: 2BHK-F9-GF\\nFlat no: F9\\nFloor: GF\\nClient Name: MANISHA SODHI\\nMeter No.: 22102731\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 97701102.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F10-SF (flat F10-SF).", "output": "Unit_ID: 2BHK-F10-SF\\nFlat no: F10\\nFloor: SF\\nClient Name: Mr. Rajwinder Kaur w/o Jaskaran Singh/tajinder Kaur (dr Hartej)\\nMeter No.: 22102737\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 97701102.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F10-FF (flat F10-FF).", "output": "Unit_ID: 2BHK-F10-FF\\nFlat no: F10\\nFloor: FF\\nClient Name: MANISHA SODHI\\nMeter No.: 22102739\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 97701102.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F10-GF (flat F10-GF).", "output": "Unit_ID: 2BHK-F10-GF\\nFlat no: F10\\nFloor: GF\\nClient Name: MANISHA SODHI\\nMeter No.: 22102736\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 97701102.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F15-SF (flat F15-SF).", "output": "Unit_ID: 2BHK-F15-SF\\nFlat no: F15\\nFloor: SF\\nClient Name: S. Kashmir Singh s/o S. Mehain Singh/Harpreet (Dr Hargun)\\nMeter No.: 20098564\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 97701102.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F15-FF (flat F15-FF).", "output": "Unit_ID: 2BHK-F15-FF\\nFlat no: F15\\nFloor: FF\\nClient Name: Geeta Khurana\\nMeter No.: 20098564\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 97701102.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F15-GF (flat F15-GF).", "output": "Unit_ID: 2BHK-F15-GF\\nFlat no: F15\\nFloor: GF\\nClient Name: MANISHA SODHI\\nMeter No.: 20098564\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 97701102.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F16-SF (flat F16-SF).", "output": "Unit_ID: 2BHK-F16-SF\\nFlat no: F16\\nFloor: SF\\nClient Name: Sh. Rahul Gautam s/o Kapil Dev Gautam//Anjana Gautam\\nMeter No.: 20098507\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 97701102.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F16-FF (flat F16-FF).", "output": "Unit_ID: 2BHK-F16-FF\\nFlat no: F16\\nFloor: FF\\nClient Name: Amarjeet Kaur\\nMeter No.: 20098507\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 97701102.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F16-GF (flat F16-GF).", "output": "Unit_ID: 2BHK-F16-GF\\nFlat no: F16\\nFloor: GF\\nClient Name: DIVYA KAPOOR\\nMeter No.: 20098507\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 97701102.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F17-SF (flat F17-SF).", "output": "Unit_ID: 2BHK-F17-SF\\nFlat no: F17\\nFloor: SF\\nClient Name: RANJIT SINGH BHANGU\\nMeter No.: 21082125\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 97701102.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F17-FF (flat F17-FF).", "output": "Unit_ID: 2BHK-F17-FF\\nFlat no: F17\\nFloor: FF\\nClient Name: Prabhjot Kalsi\\nMeter No.: 22102863\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 97701102.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F17-GF (flat F17-GF).", "output": "Unit_ID: 2BHK-F17-GF\\nFlat no: F17\\nFloor: GF\\nClient Name: Prabhjot Kalsi\\nMeter No.: 22102861\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 97701102.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F18-SF (flat F18-SF).", "output": "Unit_ID: 2BHK-F18-SF\\nFlat no: F18\\nFloor: SF\\nClient Name: Mrs. Gulati\\nMeter No.: 21129915\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 97701102.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F18-FF (flat F18-FF).", "output": "Unit_ID: 2BHK-F18-FF\\nFlat no: F18\\nFloor: FF\\nClient Name: S. Salwant Singh s/o Sh. Chanan Singh AND Smt. Puro Kaur w/o S. Salwant Singh\\nMeter No.: 22102943\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 97701102.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F18-GF (flat F18-GF).", "output": "Unit_ID: 2BHK-F18-GF\\nFlat no: F18\\nFloor: GF\\nClient Name: Surinderjit Singh\\nMeter No.: 21082123\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 97701102.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F19-SF (flat F19-SF).", "output": "Unit_ID: 2BHK-F19-SF\\nFlat no: F19\\nFloor: SF\\nClient Name: Dr. Prem Rana \\nMeter No.: 19152172\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729926.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F19-FF (flat F19-FF).", "output": "Unit_ID: 2BHK-F19-FF\\nFlat no: F19\\nFloor: FF\\nClient Name: Regent Land Holdings Pvt Ltd\\nMeter No.: 19152172\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729926.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F19-GF (flat F19-GF).", "output": "Unit_ID: 2BHK-F19-GF\\nFlat no: F19\\nFloor: GF\\nClient Name: Dr. Prem Rana \\nMeter No.: 19152172\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729926.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F20-SF (flat F20-SF).", "output": "Unit_ID: 2BHK-F20-SF\\nFlat no: F20\\nFloor: SF\\nClient Name: Mr. Gunjan Dua s/o Sh. Harish dua\\nMeter No.: 19152169\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729926.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F20-FF (flat F20-FF).", "output": "Unit_ID: 2BHK-F20-FF\\nFlat no: F20\\nFloor: FF\\nClient Name: Mrs. Renu Aggarwal w/o Rakesh Kumar Aggarwal AND Mr. Rakesh Kumar Aggarwal s/o Darshan Kumar Aggarwal \\nMeter No.: 19152169\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729926.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F20-GF (flat F20-GF).", "output": "Unit_ID: 2BHK-F20-GF\\nFlat no: F20\\nFloor: GF\\nClient Name: vijay kumar baheri\\nMeter No.: 22102940\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729926.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F21-SF (flat F21-SF).", "output": "Unit_ID: 2BHK-F21-SF\\nFlat no: F21\\nFloor: SF\\nClient Name: S. Jagnandan Bir Singh s/o S. Narottam Singh\\nMeter No.: 20098575\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729926.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F21-FF (flat F21-FF).", "output": "Unit_ID: 2BHK-F21-FF\\nFlat no: F21\\nFloor: FF\\nClient Name: Mr. Gautam Jain s/o Paras Das Jain and Rakesh Kumar Aggarwal S/o Darshan Kumar aggarwal\\nMeter No.: 20098575\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729926.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F21-GF (flat F21-GF).", "output": "Unit_ID: 2BHK-F21-GF\\nFlat no: F21\\nFloor: GF\\nClient Name: nirmal singh sandhu\\nMeter No.: 20098575\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729926.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F22-SF (flat F22-SF).", "output": "Unit_ID: 2BHK-F22-SF\\nFlat no: F22\\nFloor: SF\\nClient Name: Smt. Avtar Kaur w/o S. Rattan Singh\\nMeter No.: 24195889\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729926.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F22-FF (flat F22-FF).", "output": "Unit_ID: 2BHK-F22-FF\\nFlat no: F22\\nFloor: FF\\nClient Name: QAZI HILAL AHMAD\\nMeter No.: 24195890\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729926.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F22-GF (flat F22-GF).", "output": "Unit_ID: 2BHK-F22-GF\\nFlat no: F22\\nFloor: GF\\nClient Name: nirmal singh sandhu\\nMeter No.: 20098574\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729926.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F23-SF (flat F23-SF).", "output": "Unit_ID: 2BHK-F23-SF\\nFlat no: F23\\nFloor: SF\\nClient Name: Mr. Sunil Kumar s/o Hari Shankar Singh\\nMeter No.: 24195892\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729926.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F23-FF (flat F23-FF).", "output": "Unit_ID: 2BHK-F23-FF\\nFlat no: F23\\nFloor: FF\\nClient Name: S. Maninder Singh s/o S. Rewel Singh AND Smt. Sumandeep Kaur w/o S. Maninder Singh\\nMeter No.: 20098573\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729926.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit 2BHK-F23-GF (flat F23-GF).", "output": "Unit_ID: 2BHK-F23-GF\\nFlat no: F23\\nFloor: GF\\nClient Name: nirmal singh sandhu\\nMeter No.: 24195891\\nFixed Charge: ₹1474\\nRate Per Unit: ₹12\\nWater Motor Meter No: 86729926.0\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit MOTOR-B (flat B5, B6, B17, B18-nan).", "output": "Unit_ID: MOTOR-B\\nFlat no: B5, B6, B17, B18\\nFloor: nan\\nClient Name: Regent Land Holdings Pvt Ltd\\nMeter No.: 87923504\\nFixed Charge: ₹0\\nRate Per Unit: ₹12\\nWater Motor Meter No: nan\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit MOTOR-C (flat C8, C9, C10, C11, C14, C15, C16, C17-nan).", "output": "Unit_ID: MOTOR-C\\nFlat no: C8, C9, C10, C11, C14, C15, C16, C17\\nFloor: nan\\nClient Name: Regent Land Holdings Pvt Ltd\\nMeter No.: 86729933\\nFixed Charge: ₹0\\nRate Per Unit: ₹12\\nWater Motor Meter No: nan\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit MOTOR-D1 (flat D1, D2, D3, D4-nan).", "output": "Unit_ID: MOTOR-D1\\nFlat no: D1, D2, D3, D4\\nFloor: nan\\nClient Name: Regent Land Holdings Pvt Ltd\\nMeter No.: 90199696\\nFixed Charge: ₹0\\nRate Per Unit: ₹12\\nWater Motor Meter No: nan\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit MOTOR-D2 (flat D6, D7, D8, D9, D10, D11-nan).", "output": "Unit_ID: MOTOR-D2\\nFlat no: D6, D7, D8, D9, D10, D11\\nFloor: nan\\nClient Name: Regent Land Holdings Pvt Ltd\\nMeter No.: 19152168\\nFixed Charge: ₹0\\nRate Per Unit: ₹12\\nWater Motor Meter No: nan\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit MOTOR-F1 (flat F2, F3, F4, F5, F6, F19, F20, F21, F22, F23-nan).", "output": "Unit_ID: MOTOR-F1\\nFlat no: F2, F3, F4, F5, F6, F19, F20, F21, F22, F23\\nFloor: nan\\nClient Name: Regent Land Holdings Pvt Ltd\\nMeter No.: 86729926\\nFixed Charge: ₹0\\nRate Per Unit: ₹12\\nWater Motor Meter No: nan\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit MOTOR-F2 (flat F7, F8, F9, F10, F15, F16, F17, F18-nan).", "output": "Unit_ID: MOTOR-F2\\nFlat no: F7, F8, F9, F10, F15, F16, F17, F18\\nFloor: nan\\nClient Name: Regent Land Holdings Pvt Ltd\\nMeter No.: 97701102\\nFixed Charge: ₹0\\nRate Per Unit: ₹12\\nWater Motor Meter No: nan\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit VILLA-A2 (flat A2).", "output": "Unit_ID: VILLA-A2\\nFlat no: A2\\nClient Name: RAMANBIR KAUR\\nMeter No.: 19151952\\nFixed Charge: ₹1857\\nRate Per Unit: ₹12\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit VILLA-A6&A7 (flat A6 & A7).", "output": "Unit_ID: VILLA-A6&A7\\nFlat no: A6 & A7\\nClient Name: SHARANJEET SINGH\\nMeter No.: 628544\\nFixed Charge: ₹1857\\nRate Per Unit: ₹12\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit VILLA-C34&35 (flat C34 & C35).", "output": "Unit_ID: VILLA-C34&35\\nFlat no: C34 & C35\\nClient Name: RANDHIR SINGH\\nMeter No.: 10094\\nFixed Charge: ₹1857\\nRate Per Unit: ₹12\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit VILLA-C42 (flat C42).", "output": "Unit_ID: VILLA-C42\\nFlat no: C42\\nClient Name: PARKASH KAUR\\nMeter No.: 17154743\\nFixed Charge: ₹1857\\nRate Per Unit: ₹12\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit VILLA-D18 (flat D18).", "output": "Unit_ID: VILLA-D18\\nFlat no: D18\\nClient Name: GURCHARAN JI/jasbir Kaur\\nMeter No.: 2102834\\nFixed Charge: ₹1857\\nRate Per Unit: ₹12\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit VILLA-D19 (flat D19).", "output": "Unit_ID: VILLA-D19\\nFlat no: D19\\nClient Name: GURINDER KAUR\\nMeter No.: 23103931\\nFixed Charge: ₹1857\\nRate Per Unit: ₹12\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit VILLA-D20 (flat D20).", "output": "Unit_ID: VILLA-D20\\nFlat no: D20\\nClient Name: HIMANSHU/Rishabh Pawa\\nMeter No.: 23103939\\nFixed Charge: ₹1857\\nRate Per Unit: ₹12\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit VILLA-D21 (flat D21).", "output": "Unit_ID: VILLA-D21\\nFlat no: D21\\nClient Name: MANAH MASIH\\nMeter No.: 22102402\\nFixed Charge: ₹1857\\nRate Per Unit: ₹12\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit VILLA-D23 (flat D23).", "output": "Unit_ID: VILLA-D23\\nFlat no: D23\\nClient Name: PARMINDER KAUR\\nMeter No.: 23103821\\nFixed Charge: ₹1857\\nRate Per Unit: ₹12\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit VILLA-D24 (flat D24).", "output": "Unit_ID: VILLA-D24\\nFlat no: D24\\nClient Name: Smriti/ Rohit Shukla\\nMeter No.: 24114216\\nFixed Charge: ₹1857\\nRate Per Unit: ₹12\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit VILLA-B26 (flat B26).", "output": "Unit_ID: VILLA-B26\\nFlat no: B26\\nClient Name: YASMEEN RANDHAWA\\nMeter No.: 22102833\\nFixed Charge: ₹1857\\nRate Per Unit: ₹12\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit SCO-2 (flat 2).", "output": "Unit_ID: SCO-2\\nFlat no: 2\\nClient Name: A TO Z Store\\nMeter No.: 19151951\\nFixed Charge: ₹2157\\nRate Per Unit: ₹12\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit SCO-3 (flat 3).", "output": "Unit_ID: SCO-3\\nFlat no: 3\\nClient Name: OLD SCHOOL/JUGAAD SINGH\\nMeter No.: 20098577\\nFixed Charge: ₹2157\\nRate Per Unit: ₹12\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit SCO-4 (flat 4).", "output": "Unit_ID: SCO-4\\nFlat no: 4\\nClient Name: NDFM BUSINESS\\nMeter No.: 24114399\\nFixed Charge: ₹2157\\nRate Per Unit: ₹12\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit SCO-5 (flat 5).", "output": "Unit_ID: SCO-5\\nFlat no: 5\\nClient Name: ADD MORE\\nMeter No.: 29102948\\nFixed Charge: ₹2157\\nRate Per Unit: ₹12\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit SCO-8 (flat 8).", "output": "Unit_ID: SCO-8\\nFlat no: 8\\nClient Name: RAJESH GUPTA/MANJIT KAUR\\nMeter No.: 18148633\\nFixed Charge: ₹2157\\nRate Per Unit: ₹12\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit SCO-9 (flat 9).", "output": "Unit_ID: SCO-9\\nFlat no: 9\\nClient Name: SYNERGY\\nMeter No.: \\nFixed Charge: ₹2157\\nRate Per Unit: ₹12\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit SCO-12 (flat 12).", "output": "Unit_ID: SCO-12\\nFlat no: 12\\nClient Name: SACHIN ARORA\\nMeter No.: 572839\\nFixed Charge: ₹2157\\nRate Per Unit: ₹12\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit SCO-13 (flat 13).", "output": "Unit_ID: SCO-13\\nFlat no: 13\\nClient Name: KAWALJEET KAUR\\nMeter No.: \\nFixed Charge: ₹2157\\nRate Per Unit: ₹12\\nPhone Number: \\nEmail: "}
{"input": "Provide the master data details for unit SCO-14 (flat 14).", "output": "Unit_ID: SCO-14\\nFlat no: 14\\nClient Name: GJ SINGH\\nMeter No.: \\nFixed Charge: ₹2157\\nRate Per Unit: ₹12\\nPhone Number: \\nEmail: "}
`;
