-- Normalized Supabase schema (Postgres)
--
-- This schema matches the tables used by DatabaseService in Supabase REST mode.
-- It is intentionally minimal: only tables/columns referenced by the Streamlit app
-- and services are included.

begin;

-- Reference tables
create table if not exists public.floors (
    id bigint generated by default as identity primary key,
    code text not null unique,
    name text
);

create table if not exists public.flat_types (
    id bigint generated by default as identity primary key,
    name text not null unique,
    monthly_fee numeric
);

create table if not exists public.owners (
    id bigint generated by default as identity primary key,
    name text,
    phone text,
    email text
);

-- Motors (shared utilities, e.g. water pump)
create table if not exists public.motors (
    id bigint generated by default as identity primary key,
    name text,
    description text,
    horsepower numeric
);

-- Core entities
create table if not exists public.flats (
    id bigint generated by default as identity primary key,
    code text not null unique,
    floor_id bigint references public.floors(id),
    type_id bigint references public.flat_types(id)
);

-- Flat-to-motor mapping for shared cost allocation
create table if not exists public.flat_motors (
    id bigint generated by default as identity primary key,
    flat_id bigint not null references public.flats(id) on delete cascade,
    motor_id bigint not null references public.motors(id) on delete cascade,
    start_date date,
    end_date date
);

create index if not exists idx_flat_motors_flat_id on public.flat_motors(flat_id);
create index if not exists idx_flat_motors_motor_id on public.flat_motors(motor_id);

create table if not exists public.flat_owners (
    id bigint generated by default as identity primary key,
    flat_id bigint not null references public.flats(id) on delete cascade,
    owner_id bigint not null references public.owners(id) on delete cascade,
    is_primary boolean default false
);

create index if not exists idx_flat_owners_flat_id on public.flat_owners(flat_id);
create index if not exists idx_flat_owners_owner_id on public.flat_owners(owner_id);

create table if not exists public.meters (
    id bigint generated by default as identity primary key,
    meter_number text not null unique,
    flat_id bigint references public.flats(id) on delete set null,
    motor_id bigint references public.motors(id) on delete set null,
    status text not null default 'active'
);

create index if not exists idx_meters_flat_id on public.meters(flat_id);
create index if not exists idx_meters_status on public.meters(status);

-- Readings
create table if not exists public.readings (
    id bigint generated by default as identity primary key,
    meter_id bigint not null references public.meters(id) on delete cascade,
    reading_date date not null,
    reading_value numeric not null,
    consumption numeric,

    -- Optional denormalized fields (the UI may write/read these)
    unit_id text,
    flat_no text,
    floor text,
    type text,
    client_name text,

    created_at timestamptz not null default now()
);

create index if not exists idx_readings_meter_id on public.readings(meter_id);
create index if not exists idx_readings_reading_date on public.readings(reading_date);

-- Bills
create table if not exists public.bills (
    id bigint generated by default as identity primary key,
    flat_id bigint not null references public.flats(id) on delete restrict,

    billing_period_start date not null,
    billing_period_end date not null,
    due_date date not null,

    flat_units numeric not null default 0,
    motor_units numeric not null default 0,
    total_units numeric not null default 0,
    total_amount numeric not null default 0,

    -- Optional fields referenced in some flows/docs
    water_motor_share numeric,
    previous_outstanding numeric,
    flat_reading_id bigint references public.readings(id) on delete set null,
    motor_reading_id bigint references public.readings(id) on delete set null,

    status text not null default 'pending',

    created_at timestamptz not null default now(),
    updated_at timestamptz
);

-- Critical business constraint: never overwrite bills for a period.
create unique index if not exists bills_flat_id_billing_period_start_key
    on public.bills(flat_id, billing_period_start);

create index if not exists idx_bills_status on public.bills(status);
create index if not exists idx_bills_created_at on public.bills(created_at);

-- Notifications (Discord/WhatsApp audit log)
create table if not exists public.notifications (
    id bigint generated by default as identity primary key,
    bill_id bigint references public.bills(id) on delete set null,
    customer_id text,
    channel text not null,
    message text not null,
    status text default 'pending',
    whatsapp_message_id text,
    sent_at timestamptz not null default now()
);

create index if not exists idx_notifications_bill_id on public.notifications(bill_id);
create index if not exists idx_notifications_customer_id on public.notifications(customer_id);

-- Stripe webhook events
create table if not exists public.payment_events (
    id bigint generated by default as identity primary key,
    bill_id bigint references public.bills(id) on delete set null,
    event_type text not null,
    payment_link_id text,
    stripe_event_id text,
    customer_id text,
    amount numeric,
    currency text,
    status text,
    event_data jsonb,
    received_at timestamptz not null default now()
);

create index if not exists idx_payment_events_bill_id on public.payment_events(bill_id);
create index if not exists idx_payment_events_stripe_event_id on public.payment_events(stripe_event_id);

commit;
